version: '3'

networks:
  core:
    external: true

#BEGIN KAFKA
services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    container_name: zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - '2181:2181'
    networks:
      - core
  kafka:
    image: 'bitnami/kafka:latest'
    container_name: kafka
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
    networks:
      - core
#END KAFKA

#BEGIN MYSQL
  001fintech-mysql:
    image: mysql:5.7
    container_name: 001fintech-mysql
    working_dir: /var/data
    command: mysqld
    expose:
      - "3306"
    ports:
      - "43306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=001fintech
      - MYSQL_DATABASE=fintech
      - MYSQL_USER=001fintech
      - MYSQL_PASSWORD=001fintech
    volumes:
      - ./mysql/volume/mysql:/var/lib/mysql
      - ./mysql/volume/data:/var/data
    networks: 
      - core
#END MYSQL